
package ua.profitsoft.strymeneshenko.generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "evo", targetNamespace = "http://www.profItsoft.org/ContractService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Evo {


    /**
     * 
     * @param getAllContractsRequest
     * @return
     *     returns ua.profitsoft.strymeneshenko.generate.GetAllContractsResponse
     */
    @WebMethod
    @WebResult(name = "getAllContractsResponse", targetNamespace = "http://www.profItsoft.org/ContractService", partName = "getAllContractsResponse")
    public GetAllContractsResponse getAllContracts(
        @WebParam(name = "getAllContractsRequest", targetNamespace = "http://www.profItsoft.org/ContractService", partName = "getAllContractsRequest")
        Object getAllContractsRequest);

}
