
package ua.profitsoft.strymeneshenko.generate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EvoService", targetNamespace = "http://www.profItsoft.org/ContractService", wsdlLocation = "http://localhost:8080/strymeneshenko_Web_exploded/ws/evo/myWebService.wsdl")
public class EvoService
    extends Service
{

    private final static URL EVOSERVICE_WSDL_LOCATION;
    private final static WebServiceException EVOSERVICE_EXCEPTION;
    private final static QName EVOSERVICE_QNAME = new QName("http://www.profItsoft.org/ContractService", "EvoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/strymeneshenko_Web_exploded/ws/evo/myWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVOSERVICE_WSDL_LOCATION = url;
        EVOSERVICE_EXCEPTION = e;
    }

    public EvoService() {
        super(__getWsdlLocation(), EVOSERVICE_QNAME);
    }

    public EvoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVOSERVICE_QNAME, features);
    }

    public EvoService(URL wsdlLocation) {
        super(wsdlLocation, EVOSERVICE_QNAME);
    }

    public EvoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVOSERVICE_QNAME, features);
    }

    public EvoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EvoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Evo
     */
    @WebEndpoint(name = "evoSoap11")
    public Evo getEvoSoap11() {
        return super.getPort(new QName("http://www.profItsoft.org/ContractService", "evoSoap11"), Evo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Evo
     */
    @WebEndpoint(name = "evoSoap11")
    public Evo getEvoSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.profItsoft.org/ContractService", "evoSoap11"), Evo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVOSERVICE_EXCEPTION!= null) {
            throw EVOSERVICE_EXCEPTION;
        }
        return EVOSERVICE_WSDL_LOCATION;
    }

}
